[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@forge/=lib/forge-std/src/",
    "@aave/=lib/aave-v3-core/contracts/",
    "@openzeppelin/=lib/openzeppelin-contracts/contracts/"
]
solc_version = "0.8.19"
optimizer = true
optimizer_runs = 200
